CREATE TABLE MATERIAS
(
    ID INT PRIMARY KEY IDENTITY(1,1)
    , NOMBRE VARCHAR(30) NOT NULL
    , DESCRIPCION VARCHAR(500) NULL
)

CREATE TABLE ESTUDIANTES
(
    ID INT PRIMARY KEY IDENTITY(1,1)
    , NOMBRE VARCHAR(150) NOT NULL
    , CORREO VARCHAR(300) NULL
)

CREATE TABLE TAREAS
(
    ID INT PRIMARY KEY IDENTITY(1,1)
    , TITULO VARCHAR(50) NOT NULL
    , FECHADENTREGA DATE DEFAULT(CONVERT(DATE, DATEADD(DAY, 15, GETDATE())))
    , COMPLETADO BIT DEFAULT(0)
    , ESTUDIANTEID INT FOREIGN KEY REFERENCES ESTUDIANTES(ID)
    , MATERIA INT FOREIGN KEY REFERENCES MATERIAS(ID)
)

INSERT INTO ESTUDIANTES VALUES('Estudiante 2', 'Correo')
INSERT INTO ESTUDIANTES VALUES('Estudiante 1', 'correo@mail.com')
SELECT * FROM ESTUDIANTES
UPDATE ESTUDIANTES
SET
    NOMBRE='Estudiante 1'
WHERE ID=1

UPDATE ESTUDIANTES
SET
    NOMBRE='Estudiante 2'
WHERE ID=2

SELECT [ID],
[NOMBRE],
[CORREO] FROM ESTUDIANTES

--INSERT INTO MATERIAS VALUES('MATERIA 1')
/*
Este insert falla porque estamos metiendo menos campos de los que necesita 
la tabla
*/

INSERT INTO MATERIAS(NOMBRE) VALUES('MATERIA 1')

INSERT INTO MATERIAS VALUES ('Materia 2', 'Materia de prueba')
SELECT * FROM MATERIAS

INSERT INTO TAREAS VALUES ('Homework 2', '2025-03-12', 0, 2, 1)
Select * FROM TAREAS

SELECT
    T.TITULO,
    T.FECHADENTREGA,
    T.COMPLETADO,
    E.NOMBRE "Nombre Alumno",
    M.NOMBRE "Nombre materia"
FROM TAREAS T 
INNER JOIN ESTUDIANTES E ON E.ID = T.ESTUDIANTEID
INNER JOIN MATERIAS M ON M.ID = T.MATERIA 