CREATE TABLE TAREAS
(
    ID INT PRIMARY KEY IDENTITY(1,1)
    , TITULO VARCHAR(50) NOT NULL
    , FECHAENTREGA DATE DEFAULT(CONVERT(DATE, DATEADD(DAY, 15, GETDATE())))
    , COMPLETADO BIT DEFAULT(0)
    , DESCRIPCION VARCHAR(500) NULL
    , ESTUDIANTEID INT FOREIGN KEY REFERENCES ESTUDIANTES(ID)
    , MATERIAID INT FOREIGN KEY REFERENCES MATERIAS(ID)
)
GO

DROP TABLE IF EXISTS TAREAS