CREATE TABLE TAREAS
(
    ID INT PRIMARY KEY IDENTITY(1,1)
    , TITULO VARCHAR(50) NOT NULL
    , FECHADENTREGA DATE DEFAULT(CONVERT(DATE, DATEADD(DAY, 15, GETDATE())))
    , COMPLETADO BIT DEFAULT(0)
    , ESTUDIANTEID INT FOREIGN KEY REFERENCES ESTUDIANTES(ID)
    , MATERIA INT FOREIGN KEY REFERENCES MATERIAS(ID)
    , DESCRIPCION VARCHAR(500) NULL
)
ALTER TABLE TAREAS
ADD DESCRICPION VARCHAR(500) NULL